# Core dependencies

[[constraint]]
  name = "github.com/tableaux-project/tableaux"
  branch = "master"

# Logging dependencies

[[constraint]]
  name = "gopkg.in/birkirb/loggers.v1"
  version = "1.0.3"

# Server dependencies

[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.4.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
